git:
  depth: 3

env:
  - TZ=Asia/Tokyo

jobs:
  include:
    - stage: Test
      name: build test my Vim in Docker container
      if: branch = master
      os: linux
      dist: xenial
      sudo: false
      language: generic
      services:
        - docker
      script:
        - docker build --tag ${TRAVIS_REPO_SLUG} .
    - stage: Deploy
      name: deploy my Vim for Linux
      if: branch = master
      os: linux
      dist: xenial
      sudo: false
      language: c
      compiler: gcc
      cache: ccache
      addons:
        apt:
          packages:
            - autoconf
            - build-essential
            - git
            - liblua5.1-dev
            - libluajit-5.1-dev
            - libncurses-dev
            - lua5.1
            - luajit
            - python3
            - python3-dev
          update: true
      env:
        - ARCHIVE=vim-${TRAVIS_OS_NAME}
        - PATH=/opt/guilt/bin:${PATH}
      script:
        - true
      before_deploy:
        - make set-git-user clone
        - make -C ./guilt PREFIX=/opt/guilt install
        - make apply-patch
        - cd ./vim-kaoriya/vim
        - ./configure --prefix=/tmp/vim $(make --no-print-directory -C ../../ print-configure)
        - make -j $(make --no-print-directory -C ../../ print-cpu-count)
        - make -j $(make --no-print-directory -C ../../ print-cpu-count) install
        - cd -
        - sed -i.bak -r -e 's|\<root\>|travis|g' ./vim-kaoriya/build/xubuntu/Makefile
        - make -C ./vim-kaoriya/build/xubuntu VIM_DIR=/tmp/vim/share/vim install
        - cd /tmp
        - tar czf ${ARCHIVE}.tar.gz ./vim
        - tar cJf ${ARCHIVE}.tar.xz ./vim
        - zip -r ${ARCHIVE}.zip ./vim
        - cd -
        - git tag ${TRAVIS_TAG:-$(date +%Y%m%dT%H%M%S)}
      deploy:
        provider: releases
        api_key:
          secure: "zZauppSIVpGJJHGmn9yO5amswu84PEsxTmbJdANdOwlkJmL7QIK3jA1mzapOg4lvNKJ2pXBc2EkxbZr7s2tAMNqWzFWW0izBTO8lxOnA/OCQ2nTLDGNgPkQ3Aj1wJT5A18WOsYNtRptRk7SEamZHd9OUF+YNgPbg4dbrjOxMygL10HMp7BoHBC+h7INgvkqDpTa2dOpLybYQardlYlGDMGsYzzlZNsUyMgLLA/oJdD/BFc9iXHs55D4nJGUQgMIVQbKSyycUIVpyLGxRagpEhYEf4f48MddN36mjxchxh3jbOjmOQbpQc2OK6FZq/3NDflujiDMo5DulwPMFF2q2OKvScVwhV6LUTNQLLqAkSIJAUqFxNWghihsWlh+fGpYNAeuD49S0sCw+1bmqgQ9NHtSYR0nN9Soe0/Qw6GgdPcPo8CVVKF9k2j7dvw9ShR19JCkf7Z6NteQMxuXp8Z+0TOGfT92fMNNCkz3wz/ZwmwpOmMvtZCUzscu4GQsLDe6RHnOUUXn8dc2XcbYg77Su7BA2cWqwmsN+62Xk9envyjer81HHTO2VaEjvZTQLV0rvsBTQS8w7f0mAge8Rcy4olwPxnNPZZOAr+PgXvoNsC/JHy6k6zqLqfdAYEkpuTA7Ua1djz8hnHlH6gmZN7Gwj+EuwAh0FSlgK5aKEmRDmuDE="
        file: '/tmp/vim-*'
        file_glob: true
        skip_cleanup: true
        on:
          branch: master
          repo: sasaplus1/vim
