if: tag IS blank

git:
  depth: 3

env:
  - TZ=Asia/Tokyo

jobs:
  include:
    - stage: Test
      name: build test my Vim in Alpine Docker container
      os: linux
      dist: xenial
      sudo: false
      language: generic
      services:
        - docker
      env:
        - TAG=${TRAVIS_REPO_SLUG}-alpine
      script:
        - docker build --tag ${TAG} -f ./dockerfiles/alpine/Dockerfile .
      after_script:
        - docker run --rm -it ${TAG} /opt/vim/bin/vim --version
    - name: build test my Vim in Ubuntu Docker container
      os: linux
      dist: xenial
      sudo: false
      language: generic
      services:
        - docker
      env:
        - TAG=${TRAVIS_REPO_SLUG}-ubuntu
      script:
        - docker build --tag ${TAG} -f ./dockerfiles/ubuntu/Dockerfile .
      after_script:
        - docker run --rm -it ${TAG} /opt/vim/bin/vim --version
    - stage: Deploy
      name: deploy my Vim for Linux
      os: linux
      dist: xenial
      sudo: false
      language: c
      compiler: gcc
      cache: ccache
      addons:
        apt:
          packages:
            - autoconf
            - build-essential
            - gettext
            - git
            - liblua5.1-dev
            - libluajit-5.1-dev
            - libncurses-dev
            - lua5.1
            - luajit
            - python
            - python-dev
            - python3
            - python3-dev
          update: true
      env:
        - ARCHIVE=vim-${TRAVIS_OS_NAME}
        - GUILT=/opt/guilt
        - PATH=${GUILT}/bin:${PATH}
      install:
        - make clone-guilt
        - make -C ./guilt PREFIX=${GUILT} install
      script:
        - true
      before_deploy:
        - make set-git-user clone-vim-kaoriya apply-patch
        - cd ./vim-kaoriya/vim
        - ./configure --prefix=/tmp/vim $(make --no-print-directory -C ../../ print-configure)
        - make -j $(make --no-print-directory -C ../../ print-cpu-count)
        - make -j $(make --no-print-directory -C ../../ print-cpu-count) install
        - cd -
        - sed -i.bak -r -e 's|\<root\>|travis|g' ./vim-kaoriya/build/xubuntu/Makefile
        - make -C ./vim-kaoriya/build/xubuntu VIM_DIR=/tmp/vim/share/vim install
        - cd /tmp
        - tar czf ${ARCHIVE}.tar.gz ./vim
        - tar cJf ${ARCHIVE}.tar.xz ./vim
        - zip -r ${ARCHIVE}.zip ./vim
        - cd -
        - export TRAVIS_TAG="${TRAVIS_COMMIT::7}-${TRAVIS_BUILD_ID}"
        - git tag "${TRAVIS_TAG}"
      deploy:
        provider: releases
        api_key:
          secure: "zZauppSIVpGJJHGmn9yO5amswu84PEsxTmbJdANdOwlkJmL7QIK3jA1mzapOg4lvNKJ2pXBc2EkxbZr7s2tAMNqWzFWW0izBTO8lxOnA/OCQ2nTLDGNgPkQ3Aj1wJT5A18WOsYNtRptRk7SEamZHd9OUF+YNgPbg4dbrjOxMygL10HMp7BoHBC+h7INgvkqDpTa2dOpLybYQardlYlGDMGsYzzlZNsUyMgLLA/oJdD/BFc9iXHs55D4nJGUQgMIVQbKSyycUIVpyLGxRagpEhYEf4f48MddN36mjxchxh3jbOjmOQbpQc2OK6FZq/3NDflujiDMo5DulwPMFF2q2OKvScVwhV6LUTNQLLqAkSIJAUqFxNWghihsWlh+fGpYNAeuD49S0sCw+1bmqgQ9NHtSYR0nN9Soe0/Qw6GgdPcPo8CVVKF9k2j7dvw9ShR19JCkf7Z6NteQMxuXp8Z+0TOGfT92fMNNCkz3wz/ZwmwpOmMvtZCUzscu4GQsLDe6RHnOUUXn8dc2XcbYg77Su7BA2cWqwmsN+62Xk9envyjer81HHTO2VaEjvZTQLV0rvsBTQS8w7f0mAge8Rcy4olwPxnNPZZOAr+PgXvoNsC/JHy6k6zqLqfdAYEkpuTA7Ua1djz8hnHlH6gmZN7Gwj+EuwAh0FSlgK5aKEmRDmuDE="
        file: '/tmp/vim-*'
        file_glob: true
        skip_cleanup: true
        on:
          all_branches: true
          repo: sasaplus1/vim
      after_deploy:
        - /tmp/vim/bin/vim --version
    - name: deploy my Vim for macOS
      os: osx
      osx_image: xcode10.2
      language: c
      compiler: clang
      cache: ccache
      addons:
        homebrew:
          packages:
            - ccache
            - coreutils
            - gettext
            - gnu-sed
            - lua@5.1
            - luajit
            - python@2
            - python@3
          update: true
      env:
        - ARCHIVE=vim-${TRAVIS_OS_NAME}
        - GUILT=/tmp/opt/guilt
        - LUA_PREFIX=$(brew --prefix)
        - PATH=${GUILT}/bin:/usr/local/opt/ccache/libexec:${PATH}
      install:
        - make clone-guilt
        - gsed -i.bak -r -e 's|\<readlink\>|greadlink|g' ./guilt/guilt
        - make -C ./guilt PREFIX=${GUILT} install
      script:
        - true
      before_deploy:
        - make set-git-user clone-vim-kaoriya apply-patch
        - cd ./vim-kaoriya/vim
        - ./configure --prefix=/tmp/vim $(make --no-print-directory -C ../../ print-configure)
        - make -j $(make --no-print-directory -C ../../ print-cpu-count)
        - make -j $(make --no-print-directory -C ../../ print-cpu-count) install
        - cd -
        - gsed -i.bak -r -e 's|\<root\>|travis|g' ./vim-kaoriya/build/freebsd/Makefile
        - make -C ./vim-kaoriya/build/freebsd VIM_DIR=/tmp/vim/share/vim kaoriya-install
        - cd /tmp
        - tar czf ${ARCHIVE}.tar.gz ./vim
        - tar cJf ${ARCHIVE}.tar.xz ./vim
        - zip -r ${ARCHIVE}.zip ./vim
        - cd -
        - export TRAVIS_TAG="${TRAVIS_COMMIT::7}-${TRAVIS_BUILD_ID}"
        - git tag "${TRAVIS_TAG}"
      deploy:
        provider: releases
        api_key:
          secure: "zZauppSIVpGJJHGmn9yO5amswu84PEsxTmbJdANdOwlkJmL7QIK3jA1mzapOg4lvNKJ2pXBc2EkxbZr7s2tAMNqWzFWW0izBTO8lxOnA/OCQ2nTLDGNgPkQ3Aj1wJT5A18WOsYNtRptRk7SEamZHd9OUF+YNgPbg4dbrjOxMygL10HMp7BoHBC+h7INgvkqDpTa2dOpLybYQardlYlGDMGsYzzlZNsUyMgLLA/oJdD/BFc9iXHs55D4nJGUQgMIVQbKSyycUIVpyLGxRagpEhYEf4f48MddN36mjxchxh3jbOjmOQbpQc2OK6FZq/3NDflujiDMo5DulwPMFF2q2OKvScVwhV6LUTNQLLqAkSIJAUqFxNWghihsWlh+fGpYNAeuD49S0sCw+1bmqgQ9NHtSYR0nN9Soe0/Qw6GgdPcPo8CVVKF9k2j7dvw9ShR19JCkf7Z6NteQMxuXp8Z+0TOGfT92fMNNCkz3wz/ZwmwpOmMvtZCUzscu4GQsLDe6RHnOUUXn8dc2XcbYg77Su7BA2cWqwmsN+62Xk9envyjer81HHTO2VaEjvZTQLV0rvsBTQS8w7f0mAge8Rcy4olwPxnNPZZOAr+PgXvoNsC/JHy6k6zqLqfdAYEkpuTA7Ua1djz8hnHlH6gmZN7Gwj+EuwAh0FSlgK5aKEmRDmuDE="
        file: '/tmp/vim-*'
        file_glob: true
        skip_cleanup: true
        on:
          all_branches: true
          repo: sasaplus1/vim
      after_deploy:
        - /tmp/vim/bin/vim --version
