os: osx

# NOTE: minimal is alias of shell
language: shell

compiler: clang

git:
  depth: 1

jobs:
  include:
    - osx_image: xcode8
    - osx_image: xcode9.2
    - osx_image: xcode10.1
    - osx_image: xcode11.3

addons:
  homebrew:
    packages:
      - autoconf
      # for gettext build
      - ccache
      - coreutils
      - gnu-sed
      - lua@5.1
      - luajit
      - python@2
      - python@3
    update: true

cache:
  directories:
    - $HOME/.ccache
    - $HOME/Library/Caches/Homebrew

env:
  global:
    - datadir=/use/local/share
    - gettext=${prefix}/share/gettext
    - prefix=/var/tmp/vim
    - version=$(sw_vers -productVersion)
    - CC=clang
    - CXX=clang++
    - PATH=${gettext}/bin:/usr/local/opt/ccache/libexec:${PATH}

before_script:
  - export -f travis_nanoseconds
  - export -f travis_fold
  - export -f travis_time_start
  - export -f travis_time_finish
  - sw_vers
  - export options=()
  - options+=(--enable-fail-if-missing)
  - options+=(--disable-smack)
  - options+=(--disable-selinux)
  - options+=(--disable-xsmp)
  - options+=(--disable-xsmp-interact)
  - options+=(--enable-luainterp=dynamic)
  - options+=(--enable-pythoninterp=dynamic)
  - options+=(--enable-python3interp=dynamic)
  - options+=(--enable-cscope)
  - options+=(--disable-netbeans)
  - options+=(--enable-terminal)
  - options+=(--enable-multibyte)
  - options+=(--disable-rightleft)
  - options+=(--disable-arabic)
  - options+=(--enable-gui=no)
  - options+=(--with-compiledby=sasa+1)
  - options+=(--with-features=huge)
  - options+=(--with-luajit)
  - options+=(--without-x)
  - options+=(--with-tlib=ncurses)
  - export configurations=${options[*]}

script:
  - >
      git config --global user.name sasaplus1 &&
      git config --global user.email '<>'
  - >
      git clone --depth 1 https://github.com/koron/guilt.git &&
      git clone --depth 1 https://github.com/koron/vim-kaoriya.git
  - >
      cd vim-kaoriya &&
      git submodule update --init -- ./patches ./vim &&
      cd -
  - gsed -i.bak -r -e 's|\<readlink\>|greadlink|g' ./guilt/guilt
  - make -C ./guilt PREFIX=/usr/local install
  - curl -fsSLO https://ftp.gnu.org/pub/gnu/gettext/gettext-0.20.1.tar.xz
  - >
      travis_fold start 'tar.gettext' &&
      travis_time_start &&
      tar fvx ./gettext-*.tar.xz &&
      travis_time_finish &&
      travis_fold end 'tar.gettext'
  - rm ./gettext-*.tar.xz
  - >
      travis_fold start 'configure.gettext' &&
      travis_time_start &&
      cd ./gettext-* &&
      ./configure
      --prefix=${gettext}
      --disable-silent-rules
      --disable-dependency-tracking
      --disable-java
      --disable-csharp
      --disable-c++
      --without-emacs
      --without-git
      --without-bzip2
      --without-xz &&
      cd - &&
      travis_time_finish &&
      travis_fold end 'configure.gettext'
  - >
      travis_fold start 'make.gettext' &&
      travis_time_start &&
      make -C ./gettext-* -j $(getconf _NPROCESSORS_ONLN) CC="ccache $CC" CXX="ccache $CXX" &&
      travis_time_finish &&
      travis_fold end 'make.gettext'
  - >
      travis_fold start 'make.install.gettext' &&
      travis_time_start &&
      make -C ./gettext-* install &&
      travis_time_finish &&
      travis_fold end 'make.install.gettext'
  - rm -rf "${gettext}/share/doc"
  - >
      cd ./vim-kaoriya/vim &&
      git checkout -b v$(printf -- '%b' 'all:\n\t@printf -- $(VIM_VER)' | make -f ../VERSION -f -) &&
      git config --local guilt.patchesdir ../patches &&
      guilt init &&
      cd -
  - >
      cd ./vim-kaoriya &&
      cp ./patches/master/* ./patches/v$(printf -- '%b' 'all:\n\t@printf -- $(VIM_VER)' | make -f ./VERSION -f -) &&
      cd -
  - >
      cd ./vim-kaoriya/vim/src &&
      guilt push --all &&
      cd -
  - make -C ./vim-kaoriya/vim/src autoconf
  - >
      travis_fold start 'build.vim' &&
      travis_time_start &&
      export LUA_PREFIX="$(brew --prefix)" &&
      export CFLAGS="-I${gettext}/include" &&
      export LDFLAGS="-L${gettext}/lib" &&
      cd ./vim-kaoriya/vim &&
      eval "./configure --prefix=${prefix} ${configurations}" &&
      make -j $(getconf _NPROCESSORS_ONLN) DATADIR=${datadir} &&
      make install &&
      cd - &&
      travis_time_finish &&
      travis_fold end 'build.vim'
  - gsed -i.bak -r -e "s|\<root\>|$(whoami)|g" ./vim-kaoriya/build/freebsd/Makefile
  - make -C ./vim-kaoriya/build/freebsd VIM_DIR="${prefix}/share/vim" kaoriya-install
  - >
      git clone --depth 1 https://github.com/vim-jp/vimdoc-ja.git "${prefix}/share/vim/plugins/vimdoc-ja" &&
      rm -rf "${prefix}/share/vim/plugins/vimdoc-ja/.git" "${prefix}/share/vim/plugins/vimdoc-ja/.gitignore"
  - cp ./pvim "${prefix}/bin/pvim"
  - >
      cd "${prefix}/bin" &&
      ln -s pvim pex &&
      ln -s pvim pview &&
      ln -s pvim pvimdiff &&
      ln -s pvim rpview &&
      ln -s pvim rpvim &&
      cd -
  - >
      install_name_tool
      -change
      "$(otool -L ${prefix}/bin/vim | awk '/libintl/ { print $1 }')"
      '@executable_path/../share/gettext/lib/libintl.dylib'
      "${prefix}/bin/vim"

before_cache:
  - brew cleanup

after_success:
  - >
    "${prefix}/bin/vim" --version
  - otool -L "${prefix}/bin/vim"

before_deploy:
  - mv "${prefix}" ./$(basename "${prefix}")-macos
  - tar cfz "vim-macos-${version}.tar.gz" ./vim-macos
  - tar cfJ "vim-macos-${version}.tar.xz" ./vim-macos
  - zip -qr "vim-macos-${version}.zip" ./vim-macos
  - >-
    sha256sum
    "vim-macos-${version}.tar.gz"
    "vim-macos-${version}.tar.xz"
    "vim-macos-${version}.zip"
    > "vim-macos-${version}-sha256sum.txt"
  - export TRAVIS_TAG="release-${TRAVIS_COMMIT}"
  - git tag "${TRAVIS_TAG}" || true

deploy:
  provider: releases
  token:
    secure: "zZauppSIVpGJJHGmn9yO5amswu84PEsxTmbJdANdOwlkJmL7QIK3jA1mzapOg4lvNKJ2pXBc2EkxbZr7s2tAMNqWzFWW0izBTO8lxOnA/OCQ2nTLDGNgPkQ3Aj1wJT5A18WOsYNtRptRk7SEamZHd9OUF+YNgPbg4dbrjOxMygL10HMp7BoHBC+h7INgvkqDpTa2dOpLybYQardlYlGDMGsYzzlZNsUyMgLLA/oJdD/BFc9iXHs55D4nJGUQgMIVQbKSyycUIVpyLGxRagpEhYEf4f48MddN36mjxchxh3jbOjmOQbpQc2OK6FZq/3NDflujiDMo5DulwPMFF2q2OKvScVwhV6LUTNQLLqAkSIJAUqFxNWghihsWlh+fGpYNAeuD49S0sCw+1bmqgQ9NHtSYR0nN9Soe0/Qw6GgdPcPo8CVVKF9k2j7dvw9ShR19JCkf7Z6NteQMxuXp8Z+0TOGfT92fMNNCkz3wz/ZwmwpOmMvtZCUzscu4GQsLDe6RHnOUUXn8dc2XcbYg77Su7BA2cWqwmsN+62Xk9envyjer81HHTO2VaEjvZTQLV0rvsBTQS8w7f0mAge8Rcy4olwPxnNPZZOAr+PgXvoNsC/JHy6k6zqLqfdAYEkpuTA7Ua1djz8hnHlH6gmZN7Gwj+EuwAh0FSlgK5aKEmRDmuDE="
  file:
    - vim-macos-*.tar.gz
    - vim-macos-*.tar.xz
    - vim-macos-*.zip
    - vim-macos-*.txt
  file_glob: true
  tag_name: ${TRAVIS_TAG}
  name: ${TRAVIS_COMMIT}
  overwrite: true
  on:
    all_branches: true
    repo: sasaplus1/vim
