os: osx

language: c

compiler: clang

git:
  depth: 1

jobs:
  include:
    - osx_image: xcode8
    - osx_image: xcode9.2
    - osx_image: xcode10.1
    - osx_image: xcode11.3

addons:
  homebrew:
    packages:
      - autoconf
      - coreutils
      # for xcode8
      - git
      - gnu-sed
      - lua@5.1
      - luajit
      - python@2
      - python@3
    update: true

env:
  global:
    - datadir=/use/local/share
    - prefix=/var/tmp/vim
    - gettext=${prefix}/share/gettext
    - PATH=${gettext}/bin:${PATH}
    - version=$(sw_vers -productVersion)

before_script:
  - export options=()
  - options+=(--enable-fail-if-missing)
  - options+=(--disable-smack)
  - options+=(--disable-selinux)
  - options+=(--disable-xsmp)
  - options+=(--disable-xsmp-interact)
  - options+=(--enable-luainterp=dynamic)
  - options+=(--enable-pythoninterp=dynamic)
  - options+=(--enable-python3interp=dynamic)
  - options+=(--enable-cscope)
  - options+=(--disable-netbeans)
  - options+=(--enable-terminal)
  - options+=(--enable-multibyte)
  - options+=(--disable-rightleft)
  - options+=(--disable-arabic)
  - options+=(--enable-gui=no)
  - options+=(--with-compiledby=sasa+1)
  - options+=(--with-features=huge)
  - options+=(--with-luajit)
  - options+=(--without-x)
  - options+=(--with-tlib=ncurses)
  - export configurations=${options[@]}

script:
  - >
      git config --global user.name sasaplus1 &&
      git config --global user.email '<>'
  - >
      git clone --depth 1 https://github.com/koron/guilt.git &&
      git clone --depth 1 https://github.com/koron/vim-kaoriya.git
  - >
      cd vim-kaoriya &&
      git submodule update --init -- ./patches ./vim &&
      cd -
  - gsed -i.bak -r -e 's|\<readlink\>|greadlink|g' ./guilt/guilt
  - make -C ./guilt PREFIX=/usr/local install
  - curl -fsSLO https://ftp.gnu.org/pub/gnu/gettext/gettext-0.20.1.tar.xz
  - tar fvx ./gettext-*.tar.xz
  - rm ./gettext-*.tar.xz
  - >
      cd ./gettext-* &&
      ./configure
      --prefix=${gettext}
      --disable-silent-rules
      --disable-dependency-tracking
      --disable-java
      --disable-csharp
      --disable-c++
      --without-emacs
      --without-git
      --without-bzip2
      --without-xz &&
      cd -
  - make -C ./gettext-* -j $(getconf _NPROCESSORS_ONLN)
  - make -C ./gettext-* install
  - rm -rf "${gettext}/share/doc"
  - >
      cd ./vim-kaoriya/vim &&
      git checkout -b v$(printf -- '%b' 'all:\n\t@printf -- $(VIM_VER)' | make -f ../VERSION -f -) &&
      git config --local guilt.patchesdir ../patches &&
      guilt init &&
      cd -
  - >
      cd ./vim-kaoriya &&
      cp ./patches/master/* ./patches/v$(printf -- '%b' 'all:\n\t@printf -- $(VIM_VER)' | make -f ./VERSION -f -) &&
      cd -
  - >
      cd ./vim-kaoriya/vim/src &&
      guilt push --all &&
      cd -
  - make -C ./vim-kaoriya/vim/src autoconf
  - >
      export LUA_PREFIX="$(brew --prefix)" &&
      export CFLAGS="-I${gettext}/include" &&
      export LDFLAGS="-L${gettext}/lib" &&
      cd ./vim-kaoriya/vim &&
      eval "./configure --prefix=${prefix} ${configurations}" &&
      make -j $(getconf _NPROCESSORS_ONLN) DATADIR=${datadir} &&
      make install &&
      cd -
  - gsed -i.bak -r -e "s|\<root\>|$(whoami)|g" ./vim-kaoriya/build/freebsd/Makefile
  - make -C ./vim-kaoriya/build/freebsd VIM_DIR="${prefix}/share/vim" kaoriya-install
  - >
      git clone --depth 1 https://github.com/vim-jp/vimdoc-ja.git "${prefix}/share/vim/plugins/vimdoc-ja" &&
      rm -rf "${prefix}/share/vim/plugins/vimdoc-ja/.git" "${prefix}/share/vim/plugins/vimdoc-ja/.gitignore"
  - cp ./pvim "${prefix}/bin/pvim"
  - >
      cd "${prefix}/bin" &&
      ln -s pvim pex &&
      ln -s pvim pview &&
      ln -s pvim pvimdiff &&
      ln -s pvim rpview &&
      ln -s pvim rpvim &&
      cd -
  - >
      install_name_tool
      -change
      "$(otool -L ${prefix}/bin/vim | awk '/libintl/ { print $1 }')"
      '@executable_path/../share/gettext/lib/libintl.dylib'
      "${prefix}/bin/vim"

after_success:
  - >
    "${prefix}/bin/vim" --version
  - otool -L "${prefix}/bin/vim"

before_deploy:
  - mv "${prefix}" ./$(basename "${prefix}")-macos
  - tar cfz "vim-macos-${version}.tar.gz" ./vim-macos
  - tar cfJ "vim-macos-${version}.tar.xz" ./vim-macos
  - zip -qr "vim-macos-${version}.zip" ./vim-macos
  - >-
    sha256sum
    "vim-macos-${version}.tar.gz"
    "vim-macos-${version}.tar.xz"
    "vim-macos-${version}.zip"
    > "vim-macos-${version}-sha256sum.txt"
  - export TRAVIS_TAG="release-${TRAVIS_COMMIT}"
  - git tag "${TRAVIS_TAG}" || true

deploy:
  provider: releases
  token:
    secure: "FhDyJl1/z9oHoDJvt/emLA0pxy5Lo1/XPA2hizgw8AuZAOeRaAYt4VHeZO59VUonHWfohFGec8LFZNTAgyrbEqdmBbOFuSN+mKcRO095tN4LIoz3mJSrhNXhLWAY9MceD1VuC6wnIzH+VRuwN3w5Cbns6m5CXOJFxUDQdhtAipaeF/BPkV4AQFEb0XbJjx5yvSWi2xCQiVVrPF8eZMGzbqNneSTn1o2OkNHe/7/1rEm2Xw1kIaClb4AmvPCam6vNTKdNrG0HwE03D5bk+TxwMdAnnox3KNIsvg0QBtEfjcyEjCrn2IWl4BMbfbQjeoQuJXnq/aZOy+tt0THKNnGAd3cc1RzHngL3qKE7p4QFnC1y1fcoAjFUIy445FbLkoAO3sbchiAWK1PPYB67+T9qurKBBHlGmS2aJlo7CbBVd26q+P2CQWJt1KOgDuEhHtO/CL042rBS1DwkVjs0Hs825g7GnK0AkTHEWxjp+SuM0ykd0CT96K5Vs+cuiNCm0ummeSpBhtXbb+PglHQTGsPntcYv0IM0KEVNF46KOl1JjH+ZlP7/TPHfhSYJ/Q+AVj9a1XLiTV15JT0toph+v3oGmQsdLVTR6Vw+Jbggf4E51MDdV1RK831gGhjqh7dLglYSP3aUhFkPBZoqCaIoj5MY4fHP5y2Ab+VqjiTWrBpD2dQ="
  file:
    - vim-macos-*.tar.gz
    - vim-macos-*.tar.xz
    - vim-macos-*.zip
    - vim-macos-*.txt
  file_glob: true
  skip_cleanup: true
  tag_name: ${TRAVIS_TAG}
  name: ${TRAVIS_COMMIT}
  overwrite: true
  on:
    all_branches: true
    repo: sasaplus1/vim
