git:
  depth: 3

jobs:
  include:
    - stage: deploy-src
      name: deploy KaoriYa patched Vim source
      os: linux
      dist: xenial
      sudo: false
      language: generic
      services:
        - docker
      script:
        - true
    - stage: deploy
      name: deploy my Vim for Linux
      os: linux
      dist: xenial
      sudo: false
      language: c
      compiler: gcc
      cache: ccache
      script:
        - true
    - name: deploy my Vim for macOS
      os: osx
      osx_image: xcode10.2
      language: c
      compiler: clang
      cache: ccache
      script:
        - true
