#!/bin/bash

set -eu
set -o pipefail

__main() {
  local support_follow=

  if readlink -f >/dev/null 2>&1
  then
    support_follow=1
  fi

  local vim=

  if [ -n "$support_follow" ]
  then
    vim="$(dirname "$(readlink -f "$0")")/vim"
  else
    if [ -L "$0" ]
    then
      local current_dir=$(pwd -P)
      local target_dir="$0"

      cd "$(dirname $target_dir)"

      while [ -L "$target_dir" ]
      do
        target_dir=$(readlink $target_dir)
        cd "$(dirname $target_dir)"
        target_dir=$(basename $target_dir)
      done

      vim="$(pwd -P)/vim"

      cd "$current_dir"
    else
      vim="$(cd "$(dirname "$0")" && pwd)/vim"
    fi
  fi

  if [ ! -x "$vim" ]
  then
    printf -- '%s\n' 'cannot execute vim.' >&2
    exit 1
  fi

  local name="$(basename "$0")"
  local options=

  case $name in
    r*)
      options="$options -Z"
      ;;
  esac

  case $name in
    *vimdiff)
      options="$options -d"
      ;;
    *view)
      options="$options -R"
      ;;
    *ex)
      options="$options -e"
      ;;
  esac

  VIM="$(dirname "$(dirname "$vim")")/share/vim" exec "$vim" $options "$@"
}
__main "$@"

unset -f __main
