#!/bin/bash

set -euo pipefail

docker run \
  --init \
  --rm \
  -v "$(pwd):/root" \
  -v /var/run/docker.sock:/var/run/docker.sock \
  -w /root \
  alpine:3.10 \
  apk add --update-cache --no-cache docker-compose && docker-compose build
