name: test

on:
  - push
  - pull_request

jobs:
  test:
    name: test
    env:
      COMPOSE_DOCKER_CLI_BUILD: 1
      TZ: Asia/Tokyo
    runs-on: ubuntu-latest
    strategy:
      matrix:
        distribution:
          - alpine
          - ubuntu
    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 1
      - run: >
          docker-compose run
          --rm ${{ matrix.distribution }}
          /opt/vim/bin/vim --version
        env:
          LANG: C
